### ISSUE TITLE
Looking for includes.php in netatmo folder

### ISSUE THREAD

**Issue by nigels0** [CFenner/MagicMirror-Netatmo-Module#13]
Hi,
I'm getting a crash on initialisation saying 
Warning: include(modules/netatmo/include.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/MagicMirror3/controllers/modules.php on line 9 from  controllers/modules.php

It seems it is looking for an include.php in the ../modules/netatmo directory, but that wasn't in the clone.

I did try adding an include.php with the contents:
```
<?php
return array(
        'js_files' => array(
                "netatmo.js"
        ),
        'css_files' => array(
                "netatmo.css"
        )
);
?>
```
didn't solve it.

It also seems to be looking for an elements.html file

**Comment by CFenner** [comment]
@nigels0 are you using the rel-1.0 branch?

**Comment by CFenner** [comment]
@nigels0 the [master](https://github.com/CFenner/MagicMirror-Netatmo-Module/tree/master) branch needs the magic mirror [v2-beta](https://github.com/MichMich/MagicMirror/tree/v2-beta) branch. 

If you are running the standard version of the mirror, use [this](https://github.com/CFenner/MagicMirror-Netatmo-Module/tree/rel-1.0) branch.

**Comment by nigels0** [comment]
OK, thanks. That must be the problem. Thanks for the fast response.

**Comment by CFenner** [comment]
Please tell me if the description to retrieve an access token is sufficient or if you like add improvements in a pull request.

**Comment by nigels0** [comment]
Actually, I could't get it working with Hurl.it, so I used the Netatmo supplied php with a mod to print out the values:

 <?php

    // This is just an example to illustrate the documentation
    // Prefer the PHP SDK

    $app_id = 'YOUR_APP_ID';
    $app_secret = 'YOUR_APP_SECRET';
    $username = 'YOUR_USERNAME';
    $password = 'YOUR_PASSWORD';
    $scope = 'read_station read_thermostat write_thermostat'; // all scopes are selected.
    $token_url = "https://api.netatmo.com/oauth2/token";
    $postdata = http_build_query(
        array(
            'grant_type' => "password",
            'client_id' => $app_id,
            'client_secret' => $app_secret,
            'username' => $username,
            'password' => $password,
            'scope' => $scope
        )
    );

    $opts = array('http' =>
    array(
        'method'  => 'POST',
        'header'  => 'Content-type: application/x-www-form-urlencoded',
        'content' => $postdata
    )
    );

    $context  = stream_context_create($opts);

    $response = file_get_contents($token_url, false, $context);
    $params = null;
    $params = json_decode($response, true);

    $api_url = "https://api.netatmo.com/api/getuser?access_token="
    . $params['access_token'];

    $user = json_decode(file_get_contents($api_url));
    echo("It worked. Hello <".$user->body->mail.">\n");
    echo ($response)
    ?>


Seemed a lot easier!

**Comment by CFenner** [comment]
Ok, than maybe I should describe this in the readme

**Comment by CFenner** [comment]
I just tried it with hurl.it and it worked fine.
