### ISSUE TITLE
MM² doesn't start with netatmo module

### ISSUE THREAD

**Issue by djsunrise19** [CFenner/MagicMirror-Netatmo-Module#14]
Hi,

the new MM² works fine. After configuring my netatmo account, `git clone` your module and changing den config.js the mirror doesn't start anymore (no error, only a black screen). I have the same problem with the sonos module. In MMv1 sonos works fine.

Do you have an idea? I checked your instructions a few times. Everything looks ok.

Regards
Maurice

**Comment by CFenner** [comment]
I'll try to look into it tonight. Have you had a look into the console?

**Comment by djsunrise19** [comment]
Okay, cool.

How can I check that on raspbian? I'm not very familiar with it.

**Comment by CFenner** [comment]
Don't know, but you could call it from your computer http://<pi_ip>:<config_port>

**Comment by djsunrise19** [comment]
I'll check that tonight. Did you get any informations already?

**Comment by CFenner** [comment]
I would expect an error in the config if the mirror doesn't start. Does it work if you remove the Netatmo module part from the config?

**Comment by djsunrise19** [comment]
Yes, then the mirror starts. The same behavior I have with the sonos module. I copied your config entrys, modify them with my keys and checked it twice. The same with your instructions. So I really don't know where the mistake could be.

**Comment by CFenner** [comment]
Now that you mention it, I think I had the same problem. Try to type the config yourself. I try to investigate this tonight.

**Comment by CFenner** [comment]
Just did a fresh setup with newest MM version and everything worked. 
I'll try to add some messages to indicate invalid refresh_tokens.

**Comment by djsunrise19** [comment]
Okay, so you think my variables aren't correct. I'll check that again.

**Comment by CFenner** [comment]
Perfect!
