### ISSUE TITLE
Measurements in german

### ISSUE THREAD

**Issue by djsunrise19** [CFenner/MagicMirror-Netatmo-Module#15]
Hi,

I've seen in `netatmo.js` that there is a chance to get all these items in german. My config file is on `de`. Did I forget something, because on my screen everything is in english:

![netatmo](https://cloud.githubusercontent.com/assets/14234570/14556149/e5f928f8-02f6-11e6-991f-fc488ac67cde.jpg)

Thank you!

**Comment by CFenner** [comment]
I planned to implement this, maybe I can do it this weekend.

**Comment by djsunrise19** [comment]
Nice to hear that. I'm curious about it.

**Comment by CFenner** [comment]
Ok, measurements can be localized now.
