### ISSUE TITLE
Temperature in Fahrenheit?

### ISSUE THREAD

**Issue by schnster** [CFenner/MagicMirror-Netatmo-Module#23]
Hi.  Love this module.  I live in the US, any chance there is a way to have the temperature displayed in Fahrenheit?  Perhaps an option in config to switch between Celcius and Fahrenheit.  Thank you for your hard work.

**Comment by CFenner** [comment]
Hi there, is your Netatmo set to Fahrenheit? I wound like so set it automatically regarding to the settings in Netatmo.

**Comment by schnster** [comment]
I believe so.  My netatmo browser page shows temperature in F.  
![screen shot 2016-10-08 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/17610243/19216282/46a50232-8d6a-11e6-9728-f2ca4216cbe5.png)

**Comment by CFenner** [comment]
Ok, and the data on the mirror is in Celsius Or just Fahrenheit with C in the end?

**Comment by schnster** [comment]
The data on the Magic Mirror is in Celcius.  See pic.  Thanks.

![img_0759](https://cloud.githubusercontent.com/assets/17610243/19216334/f82f37c4-8d6b-11e6-947f-ed066f42ef8d.JPG)

**Comment by schnster** [comment]
If you mean the default module weather obtained from Openweathermap, it was in F.

**Comment by CFenner** [comment]
Ok, as I understood the Netatmo API, the data should get out in the correct format. You can check the setting in the data you get back from Netatmo:
<img width="490" alt="bildschirmfoto 2016-10-09 um 12 47 18" src="https://cloud.githubusercontent.com/assets/9592452/19219853/8d4f0e62-8e1e-11e6-84d5-8f62e167285b.png">
Here you have the `unit` value indicating the measurement system you are using.

Could you use your browsers debugger (open the mirror ui on your computer) to trace in the module coding and set a breakpoint inside the `renderAll` method of netatmo.js. Reload the page and have a look at the data variable.
<img width="511" alt="bildschirmfoto 2016-10-09 um 12 41 31" src="https://cloud.githubusercontent.com/assets/9592452/19219845/5af05b9c-8e1e-11e6-973e-a579d2e8a4a6.png">

**Comment by schnster** [comment]
Pardon my ignorance I'm pretty new at this, but in my Chromium browser on the Pi, I think you are suggesting I use the the Developer Tools to trace the netatmo.js file in the module folder?  How do I run the mirror UI (e.g., npm start) and have the Chromium dev tool trace it?  Thanks again

**Comment by CFenner** [comment]
@schnster you just need to start the mirror as usual. Then you open your browser on your laptop and call the PIs ip: in my case it's `http://192.168.178.40:8080`
In the browser you can use the developer tools, the PIs browser Chromium has not dev tools, so you need to do this round trip.

**Comment by schnster** [comment]
Ah, thanks, that was neat!  I traced the data variable and this is what I got.  
![screen shot 2016-10-10 at 1 06 53 pm](https://cloud.githubusercontent.com/assets/17610243/19249480/a4964ac8-8eea-11e6-96b9-1e0a537f0bac.png)

**Comment by CFenner** [comment]
Ok, so different `unit` and if you look at the sensor data: body/device/0/dashboard_data is it in Celsius or Fahrenheit?

**Comment by schnster** [comment]
Temperature is in Celcius...

![screen shot 2016-10-10 at 1 20 41 pm](https://cloud.githubusercontent.com/assets/17610243/19249867/757f9152-8eec-11e6-9f25-51c9a0498836.png)

**Comment by CFenner** [comment]
Ok, I'm a bit confused, if I as an api provider would knew how the user wants his data to be displayed, then I would transform the data into this format right away. But that's only my opinion, I've just created a ticket in the netatmo forum. Hopefully someone there can tell me how to handle it. If we have bad lucky I need to implement a data conversion regarding the unit attribute.

**Comment by schnster** [comment]
OK, thanks for helping out with this!

**Comment by CFenner** [comment]
If you like to get dirty you can get into the code and do a quick fix to Fahrenheit. Go to line `191` in `netatmo.js` and change `return value.toFixed(1) + '°';` to `return (value*1,8+32).toFixed(1) + '°';`.

**Comment by schnster** [comment]
Thanks for the tip.  Looks good now!  
![screen shot 2016-10-10 at 2 35 49 pm](https://cloud.githubusercontent.com/assets/17610243/19252036/644b1dba-8ef7-11e6-8779-6ac4212ccfb2.png)

**Comment by macogle** [comment]
The quick fix suggested utilizes a comma as the decimal point in the multiplier rather than a period. This will break the code for those computers with language configurations which define the period as the decimal point, returning a value of 40º. Presumably, many users who are looking for data in Fahrenheit are also using keyboards configured for US (EN).

The correct code should read `(value*1.8+32).toFixed(1) + '°';`

**Comment by CFenner** [comment]
@macogle you are right, `18` was stupid ;) it won't work never the less which computer language you have.
