### ISSUE TITLE
change graphics

### ISSUE THREAD

**Issue by knutta** [CFenner/MagicMirror-Netatmo-Module#25]
Is there any way of changing the graphical layout of the module? I would have loved to just do it, but my coding skills is slightly insufficient do decipher how to do this... I've included a png showing some of what I have thought of. Is this an easy fix? Or is there any interest in updating the graphics? The illustration is made in illustrator, and the elements can be exported as pngs if there is any interest..
![netatmogui](https://cloud.githubusercontent.com/assets/23390082/20197934/44b1aac8-a7a2-11e6-991d-824fa52ab3cd.png)

**Comment by CFenner** [comment]
Nice idea! I can have a look at it and check if it's feasible. Can you provide designs for a wind and rain sensor as well?

**Comment by knutta** [comment]
Sure, I'll give it a go this weekend!

**Comment by knutta** [comment]
Skimmed through the FAQ-pdf, and it seems green is 0-999ppm, yellow is 1000-1999ppm and red is 2000-5000ppm. Page 21 in this if interested: http://www.vesternet.com/downloads/dl/file/id/283/netatmo_connected_weather_station_faq.pdf

A suggestion btw: is it possible to add a config-entry of opacity, where the opacity and then the intensity of the colour-blobs is adjusted? Maybe as off=0%, low=40%, medium=75% and high=100% ?

**Comment by knutta** [comment]
Here's the new draft including the wind and rain sensors.
A suggestion is to use the angle-return for wind as a variable to rotate the arrow (for wind and gust), and the image for rain could change based on amount of rain (thresholds from wikipedia). I reckon the weather is not something that is returned from netatmo? It could be a future implementation of the standard weathermodule, or I could see if I can't figure out something else to put there.
![netatmogui-01](https://cloud.githubusercontent.com/assets/23390082/20231642/b350ff30-a863-11e6-8005-a6ab8f7f318f.png)

Individual pngs as follows:
![netatmogui-02](https://cloud.githubusercontent.com/assets/23390082/20231794/97c93b64-a864-11e6-864c-bbbbb1000e87.png)
![netatmogui-03](https://cloud.githubusercontent.com/assets/23390082/20231796/97ebf7bc-a864-11e6-8230-356a5f17f719.png)
![netatmogui-04](https://cloud.githubusercontent.com/assets/23390082/20231797/97ec7c8c-a864-11e6-9353-37ad56aac4bf.png)
![netatmogui-05](https://cloud.githubusercontent.com/assets/23390082/20231798/97ed7952-a864-11e6-9a21-17e70d93878d.png)
![netatmogui-06](https://cloud.githubusercontent.com/assets/23390082/20231800/97f2cd30-a864-11e6-90a9-a39ff4bf950a.png)
![netatmogui-07](https://cloud.githubusercontent.com/assets/23390082/20231799/97eefbf6-a864-11e6-9331-36fca5a58907.png)
![netatmogui-08](https://cloud.githubusercontent.com/assets/23390082/20231795/97e62a94-a864-11e6-8448-abd412e12843.png)
![netatmogui-09](https://cloud.githubusercontent.com/assets/23390082/20231801/97feaf88-a864-11e6-921c-9a25433576fb.png)
![netatmogui-10](https://cloud.githubusercontent.com/assets/23390082/20231802/98064aa4-a864-11e6-815a-ea496a4c7ea7.png)


Let me know if you need better quality.

**Comment by knutta** [comment]
realized I forgot the max/min arrows.. And I changed the small wind-arrow to have a grey (#ccc) outline.
[gui2.zip](https://github.com/CFenner/MagicMirror-Netatmo-Module/files/586957/gui2.zip)

**Comment by CFenner** [comment]
<img width="270" alt="bildschirmfoto 2016-11-18 um 20 53 49" src="https://cloud.githubusercontent.com/assets/9592452/20444384/2add5518-add1-11e6-9989-fa9f7c936ba0.png">
Possible `HTML` coding:
```
<div class="netatmo">
<div class="name small" style="
text-align: left">Wohnzimmer</div><table class="data"><tbody><tr><td class="left" style="
vertical-align: top">
<div class="large light"><span class="bright">20.8°</span></div>
</td><td class="center" style="
width: 5em"><div style="
width: 5em;
    height: 5em;
    background-color: red;
    border-radius: 5em;
    box-shadow: inset 0 0 1em .5em black;"></div><div class="small" style="
text-align: center">877 ppm</div></td><td class="data" style="
vertical-align: bottom"><table class=""><tbody><tr><td class="small">Lautstärke</td><td class="value small">35 dB</td></tr><tr><td class="small">Luftdruck</td><td class="value small">1005 mbar</td></tr><tr><td class="small">Feuchtigkeit</td><td class="value small">58%</td></tr></tbody></table></td>
</tr></tbody>
</table>
<div class="module"><div class="data"><table class=""><tbody><tr><td class="small">Lautstärke</td><td class="value small">35 dB</td></tr><tr><td class="small">Luftdruck</td><td class="value small">1005 mbar</td></tr><tr><td class="small">CO<sub>2</sub></td><td class="value small">877 ppm</td></tr><tr><td class="small">Feuchtigkeit</td><td class="value small">58%</td></tr><tr><td class="small">Temperatur</td><td class="value small">20.8°</td></tr></tbody></table></div><div class="name small">Wohnzimmer</div></div></div>
```

**Comment by knutta** [comment]
Yeah, this looks nice! Only thing I was looking at was the screenshot showing the small text aligned to the center(?) of its coloumn so it didn't look as clean, but it looks like that is fixed in the HTML. Seems you have entered the data twice in the HTML though. I guess that's just something that you forgot to delete?

**Comment by knutta** [comment]
How is it going with this enhancement?

**Comment by CFenner** [comment]
@knutta Do toi have a wind & rain sensor? Can you grant me access to your station for testing?

**Comment by knutta** [comment]
@CFenner I haven't got any of them, and I've reached out to people I know trying to find someone with the wind or rain gauge, but sadly had no luck. I even tried asking NetatmoSupport on twitter for access to a station, but was declined...

**Comment by CFenner** [comment]
I mocked the data for wind/rain, but I forgot to take a screenshot ;)

But it should look ok now.

**Comment by knutta** [comment]
sweet! I can't wait to try out the new look myself :D

**Comment by CFenner** [comment]
Use design: 'bubbles', to activate it.

**Comment by zdeneksofr** [comment]
`design: 'bubbles'` will activate new graphics for all measurement or just for wind and rain? I don't have these sensors, but I like idea to have color indicator of Humidity. Is there simple way, how to activate it?
and it will be awsome to have possibility to adjust color of temperature measurement inside and outisde based on criteria (outised lower than 0°C -White, 0-5 blue....) Is there way now, how to do it? 

thanks, Zdeněk
