### ISSUE TITLE
module not working for me

### ISSUE THREAD

**Issue by zdeneksofr** [CFenner/MagicMirror-Netatmo-Module#28]
Hi all
I´m newbie, I´m trying to get running Netatmo module. What I´ve did:

-installed latest Magic Mirror
-installed latest upates and upgrades
-customized default modules
Until now everything OK

followed https://github.com/CFenner/MagicMirror-Netatmo-Module
-get from github
-registered new app on Netatmo API, get ClientID and Client secret
-sent POST request to Hurl.it, got valid response with “access_token” and “refresh_token”
-CTRL+C & CTRL+V entered Module section to .js including ID, Secret and Refresh_token

After run Magic mirror I´ve got black screen with yellow sign in top-right corner.
any idea, what´s wrong? or how to verify, settings?

thanks for help
Zdenek

**Comment by CFenner** [comment]
I guess this is solved? What was the issue, @zdeneksofr ?

**Comment by zdeneksofr** [comment]
solved. the problem was in typo in token. Thanks. But I've a quesion - is it possible via css change color of "Temperature"?  thanks, Zdeněk
