### ISSUE TITLE
cs language

### ISSUE THREAD

**Issue by zdeneksofr** [CFenner/MagicMirror-Netatmo-Module#36]
hi all.

I've made copy of en.json, change name to cs.json, change strings, add line to netatmo.js, so I've
```
  getTranslations: function() {
    return {
      en: 'l10n/en.json',
      de: 'l10n/de.json',
      fr: 'l10n/fr.json',
      cs: 'l10n/cs.json'
    };
  },
```
 but
- strings are still in english
- how to make it "public", I mean a part of official distribution of module and not have to type next time again

thanks, Zdenek

**Comment by CFenner** [comment]
So, to change the language, just change the config option in your [MagicMirror](https://github.com/MichMich/MagicMirror#configuration).

To make the localisation for the Netatmo module public, create a fork of this repo, do the changes again and file a pull request to this repo. After review we can merge it.

**Comment by zdeneksofr** [comment]
thanks for answer, but of course I've in config.js 	`language: 'cs',` and for other modules it works. Did I miss something else?

**Comment by CFenner** [comment]
not that I know... can you file a pull request. Then I can try it here.

**Comment by CFenner** [comment]
works for fr.. so should also for cs!

**Comment by zdeneksofr** [comment]
tried to create PULL, so I hope it's done properly

**Comment by CFenner** [comment]
Unfortunately not, you created a pull request with my own changes, not with you translation. The best is to create a new branch from master and do the changes there and create a PR.

**Comment by CFenner** [comment]
@zdeneksofr: Ok, I found the translation you did. Can you please complete it? 
https://github.com/CFenner/MagicMirror-Netatmo-Module/blob/lang-cs/l10n/cs.json

**Comment by CFenner** [comment]
It's working so far:
<img width="178" alt="bildschirmfoto 2017-05-14 um 08 36 08" src="https://cloud.githubusercontent.com/assets/9592452/26031779/709e0040-3880-11e7-8d4b-5cc5eca83324.png">
<img width="295" alt="bildschirmfoto 2017-05-14 um 08 35 59" src="https://cloud.githubusercontent.com/assets/9592452/26031780/72eba8de-3880-11e7-9607-167e2a425df8.png">

**Comment by zdeneksofr** [comment]
weird. so why not for me?

**Comment by zdeneksofr** [comment]
weird, weird, weird. I did update to get latest build, than I add again cs.json to netatmo.js and now it works. I don't get it....

**Comment by CFenner** [comment]
Did you update your MagicMirror to the most recent one?

BTW: You can activate this design with a config property (not documented yet): add `design: 'bubbles'` to your netatmo module config.

**Comment by zdeneksofr** [comment]
yes, I did. OK, now it's working, also "bubles". I just need to play with css, because in "buble" it's too big for me. Never mind, thanks a lot for quick responses and support
