### ISSUE TITLE
Font/Size & display change

### ISSUE THREAD

**Issue by jinjirosan** [CFenner/MagicMirror-Netatmo-Module#43]
First off, thx for your work and effort. It's awesome that I can display netatmo readings on my mirror now.
I've tried to customize two things but unfortunately not successful, could use your help and pointers:
1. How/where can I change the font type and size of each of the labels and data (of the classic design)?
2. Using the classic design,  how can I place the squares vertically instead of horizontally?
This way they will be nicely outlined along the side of my mirror.

I tried the .css, the design files and looking into netatmo.js but no succes yet.

**Comment by CFenner** [comment]
1. you should use the custom css file provided for the magic mirror. The style you need to add and change is: `.netatmo .classic .module .name` and `.netatmo .classic .module .data`

2. I created #44 to implement that.

**Comment by CFenner** [comment]
@jinjirosan: completed #44 

You can use `horizontal: false` in the config.

**Comment by jinjirosan** [comment]
Thx for the quick response!
The modules are now perfectly aligned vertically.

Font style change on the `.netatmo .classic .module .name` works however similar settings on the `.netatmo .classic .module .data` do not change the label/data size on temperature, CO2, etc.

**Comment by CFenner** [comment]
This is because the texts itself use the `.small` style which is defined in the MagicMirror. You need to change this one to override the font size.
